// Re-export all PDF types and generators for backward compatibility
export type { PdfWaqfInfo } from './core/core';
export { type UnitPdfRow } from './core/core';
export { generateAnnualReportPDF, generateBeneficiaryStatementPDF, generateAnnualDisclosurePDF } from './reports/reports';
export { generatePropertiesPDF, generateContractsPDF, generateBeneficiariesPDF, generateUnitsPDF } from './entities/entities';
export { generateIncomePDF, generateExpensesPDF } from './entities/expenses';
export { generateAccountsPDF, generateDistributionsPDF } from './entities/accounts';
export { generateMySharePDF, generateDisclosurePDF } from './entities/beneficiary';
export { generateInvoicesViewPDF, generateOverdueInvoicesPDF } from './invoices/invoices';
export { generateYearComparisonPDF } from './reports/comparison';
export type { YearComparisonPdfData } from './reports/comparison';
export { generateForensicAuditPDF } from './reports/forensicAudit';
export type { ForensicAuditData } from './reports/forensicAudit';
export { generateBylawsPDF } from './entities/bylaws';
export type { BylawPdfEntry } from './entities/bylaws';
export { generateAuditLogPDF } from './entities/auditLog';
export type { AuditLogPdfOptions } from './entities/auditLog';
export { generateComprehensiveBeneficiaryPDF } from './reports/comprehensiveBeneficiary';
export type { ComprehensiveBeneficiaryData } from './reports/comprehensiveBeneficiary';
export { generatePaymentInvoicePDF } from './invoices/paymentInvoice';
export type { PaymentInvoicePdfData, InvoiceTemplate } from './invoices/paymentInvoice';
export { generateAnnualReportPDF as generateAnnualAchievementsPDF } from './reports/annualReport';
export type { AnnualReportPdfData } from './reports/annualReport';
export { generateInvoiceClientPDF } from './invoices/invoice';
export type { GenerateInvoicePdfClientOptions } from './invoices/invoice';
