// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo back the provided text. Use to verify MCP connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/get-public-stats.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_public_stats_default = defineTool2({
  name: "get_public_waqf_stats",
  title: "Get public waqf statistics",
  description: "Read publicly disclosed statistics about Marzouq bin Ali Al-Thubaiti Waqf (properties, contracts, beneficiaries) as controlled by the overseer's public disclosure settings.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !key) {
      return { content: [{ type: "text", text: "Backend not configured" }], isError: true };
    }
    const supabase = createClient(url, key, { auth: { persistSession: false } });
    const { data, error } = await supabase.from("app_settings").select("key,value").like("key", "public_stats_%");
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const stats = Object.fromEntries((data ?? []).map((r) => [r.key, r.value]));
    return {
      content: [{ type: "text", text: JSON.stringify(stats, null, 2) }],
      structuredContent: { stats }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "waqf-wise-mcp",
  title: "Waqf Wise \u2014 Marzouq Al-Thubaiti Waqf",
  version: "0.1.0",
  instructions: "Public tools for Marzouq bin Ali Al-Thubaiti Waqf management system. Use `echo` to verify connectivity and `get_public_waqf_stats` to read publicly disclosed statistics.",
  tools: [echo_default, get_public_stats_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
