-- Superseded by 20260527162000_fix_publish_blocking_fiscal_year_not_null.sql.
-- This migration attempted to enforce NOT NULL on payment_invoices.fiscal_year_id,
-- but Live contains future-dated payment invoices that need a 2026-2027 fiscal year first.
